### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by vivekian** [debajit/unison-fsmonitor-mac#1]
From El Captain onwards, SIP (system integrity protection) is enabled. Perhaps the pip command needs the --user argument to install macfsevents correctly. 

pip install --user macfsevents

**Comment by debajit** [comment]
Interesting. I didn't know it affected python/ruby. I‘ve been using this same pip command on Sierra and on El Capitan successfully for about 3-4 years now (and I know it has been working for others as well with the same setup), and this works with the built-in system python as well as with Anaconda — SIP has been largely “invisible”/transparent for me I guess, though I'd like to read up more about it :) https://support.apple.com/en-us/HT204899 Thank you for letting me know, Vivek :)

**Comment by vivekian** [comment]
Thanks! This must be a local setup issue on my side then. I believe I once used sudo to do an installation and that resulted in these issues.
